### ISSUE TITLE
No versions available when installing

### ISSUE THREAD

**Issue by skript-cc** [bolt/base-widget#4]
When installing this extension in bolt, it says there are no versions available. I'm running on bolt 2.2.17.

![no-versions-to-install](https://cloud.githubusercontent.com/assets/16382453/12782744/8625d392-ca7d-11e5-93fe-936442e4ce64.png)

**Comment by skript-cc** [comment]
Tried both stable and dev as minimum stability

**Comment by GwendolenLynch** [comment]
That is because the functionality is implemented in upcoming Bolt v3, but this extension was made when Bolt's current master was going to be v2.3 but due to the size of changes got bumped to v3 and we have redone the extension API as a result. 

I have removed the tags and updated most of the extension to be theoretically compatible with Bolt v3 API now and in an hour or so should disappear from the v2 extension list in the UI

**Comment by skript-cc** [comment]
Ok, so this extension is not available at all on Bolt 2.2?

**Comment by GwendolenLynch** [comment]
No, the widget API was written by @bobdenotter and myself for the upcoming Bolt v3 and relies to the asset loaders that were implemented there.

**Comment by skript-cc** [comment]
I see, too bad.
